#!/usr/bin/env python3
import os
import sys
import numpy as np
from PIL import Image
from scipy.spatial import KDTree
import re
import argparse

def rgb565_to_rgb(val):
    r = (val >> 11) & 0x1F
    g = (val >> 5) & 0x3F
    b = val & 0x1F
    r = (r * 255) // 31
    g = (g * 255) // 63
    b = (b * 255) // 31
    return (r, g, b)

def load_palette(header_path):
    palette = []
    with open(header_path, 'r') as f:
        content = f.read()
        
    # Match the paletteRGB565 array
    match = re.search(r'paletteRGB565\[256\]\s*=\s*\{([^}]+)\}', content)
    if not match:
        raise ValueError("Could not find paletteRGB565 array in palette.h")
        
    array_content = match.group(1)
    # Extract hex values
    hex_vals = re.findall(r'0x[0-9a-fA-F]+', array_content)
    
    if len(hex_vals) != 256:
        raise ValueError(f"Expected 256 colors, found {len(hex_vals)}")
        
    for h in hex_vals:
        val = int(h, 16)
        palette.append(rgb565_to_rgb(val))
        
    return np.array(palette)

def process_image(image_path, palette, dither=False):
    img = Image.open(image_path)
    
    frames = []
    try:
        while True:
            # Convert frame to RGB
            frame = img.convert('RGB')
            frames.append(np.array(frame))
            img.seek(img.tell() + 1)
    except EOFError:
        pass

    height, width, _ = frames[0].shape
    num_frames = len(frames)
    fps = 0
    if 'duration' in img.info and img.info['duration'] > 0:
        fps = int(1000.0 / img.info['duration'])
    elif num_frames > 1:
        fps = 10 # Default fallback

    # Build KDTree for palette mapping
    tree = KDTree(palette)
    
    mapped_frames = []
    for frame in frames:
        if dither:
            # Simple Floyd-Steinberg dithering could go here
            # For this MVP, we will stick to KDTree nearest neighbor on the raw image
            # as vectorization is much faster.
            pass
            
        # Flatten frame to [N, 3], query KDTree, reshape to [height, width]
        flat_pixels = frame.reshape(-1, 3)
        _, indices = tree.query(flat_pixels)
        mapped_frame = indices.reshape((height, width)).astype(np.uint8)
        mapped_frames.append(mapped_frame)
        
    return mapped_frames, width, height, num_frames, fps

def generate_c_header(frames, width, height, num_frames, fps, output_name, struct_name):
    flat_data = []
    for frame in frames:
        flat_data.extend(frame.flatten())
        
    lines = []
    lines.append(f"// Generated by CMT (Color Mapping Tool)")
    lines.append(f"#include \"locale.h\"")
    lines.append(f"")
    
    # Write array
    lines.append(f"const uint8_t {struct_name}_data[] = {{")
    
    # Format array elements neatly
    for i in range(0, len(flat_data), 16):
        chunk = flat_data[i:i+16]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
        
    lines.append(f"}};")
    lines.append(f"")
    
    # Write struct
    lines.append(f"const LHR_MapImage {struct_name} = {{")
    lines.append(f"  .data = {struct_name}_data,")
    lines.append(f"  .width = {width},")
    lines.append(f"  .height = {height},")
    lines.append(f"  .frames = {num_frames},")
    lines.append(f"  .fps = {fps}")
    lines.append(f"}};")
    
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser(description="LHR Color Mapping Tool")
    parser.add_argument("input", help="Input image (GIF/PNG)")
    parser.add_argument("output", help="Output C header file")
    parser.add_argument("--palette", default="core/palette.h", help="Path to palette.h")
    parser.add_argument("--name", default="mapped_image", help="Name of the C struct")
    parser.add_argument("--dither", action="store_true", help="Enable Floyd-Steinberg dithering")
    args = parser.parse_args()
    
    print(f"Loading palette from {args.palette}...")
    palette = load_palette(args.palette)
    
    print(f"Processing image {args.input}...")
    frames, width, height, num_frames, fps = process_image(args.input, palette, dither=args.dither)
    
    print(f"Generating C header {args.output}...")
    c_code = generate_c_header(frames, width, height, num_frames, fps, args.output, args.name)
    
    with open(args.output, 'w') as f:
        f.write(c_code)
        
    print("Done!")

if __name__ == "__main__":
    main()
