#!/usr/bin/env python3
import os
import sys
import numpy as np
from PIL import Image
from scipy.spatial import KDTree
import re
import argparse

def rgb565_to_rgb(val):
    r = (val >> 11) & 0x1F
    g = (val >> 5) & 0x3F
    b = val & 0x1F
    r = (r * 255) // 31
    g = (g * 255) // 63
    b = (b * 255) // 31
    return (r, g, b)

def load_palette(header_path):
    palette = []
    with open(header_path, 'r') as f:
        content = f.read()
        
    # Match the paletteRGB565 array
    match = re.search(r'paletteRGB565\[256\]\s*=\s*\{([^}]+)\}', content)
    if not match:
        raise ValueError("Could not find paletteRGB565 array in palette.h")
        
    array_content = match.group(1)
    # Extract integer values (base 10)
    vals = re.findall(r'\b\d+\b', array_content)
    
    if len(vals) != 256:
        # It's possible there are two #if/#else arrays. Let's just take the first 256.
        if len(vals) >= 256:
            vals = vals[:256]
        else:
            raise ValueError(f"Expected 256 colors, found {len(vals)}")
        
    for v in vals:
        val = int(v)
        palette.append(rgb565_to_rgb(val))
        
    return np.array(palette)

def process_image(image_path, palette, dither=True, chromakey=None):
    img = Image.open(image_path)
    
    frames = []
    try:
        while True:
            # Convert frame to RGB
            frame = img.convert('RGB')
            frames.append(np.array(frame))
            img.seek(img.tell() + 1)
    except EOFError:
        pass

    height, width, _ = frames[0].shape
    num_frames = len(frames)
    fps = 0
    if 'duration' in img.info and img.info['duration'] > 0:
        fps = int(1000.0 / img.info['duration'])
    elif num_frames > 1:
        fps = 10 # Default fallback

    # Build KDTree for palette mapping
    tree = KDTree(palette)
    
    mapped_frames = []
    for frame in frames:
        if dither:
            # Floyd-Steinberg dithering
            float_frame = frame.astype(np.float32)
            mapped_frame = np.zeros((height, width), dtype=np.uint8)
            
            for y in range(height):
                for x in range(width):
                    if chromakey is not None and np.array_equal(frame[y, x], chromakey):
                        mapped_frame[y, x] = 0
                        quant_error = 0.0
                    else:
                        old_pixel = float_frame[y, x]
                        # Clamp to 0-255 before querying
                        clamped = np.clip(old_pixel, 0, 255)
                        _, idx = tree.query(clamped)
                        new_pixel = palette[idx]
                        mapped_frame[y, x] = idx
                        
                        quant_error = old_pixel - new_pixel
                    
                    if x + 1 < width:
                        float_frame[y, x + 1] += quant_error * 7 / 16
                    if y + 1 < height:
                        if x - 1 >= 0:
                            float_frame[y + 1, x - 1] += quant_error * 3 / 16
                        float_frame[y + 1, x] += quant_error * 5 / 16
                        if x + 1 < width:
                            float_frame[y + 1, x + 1] += quant_error * 1 / 16
        else:
            # Flatten frame to [N, 3], query KDTree, reshape to [height, width]
            flat_pixels = frame.reshape(-1, 3)
            _, indices = tree.query(flat_pixels)
            if chromakey is not None:
                mask = np.all(flat_pixels == chromakey, axis=-1)
                indices[mask] = 0
            mapped_frame = indices.reshape((height, width)).astype(np.uint8)
            
        mapped_frames.append(mapped_frame)
        
    return mapped_frames, width, height, num_frames, fps

def generate_c_header(frames, width, height, num_frames, fps, output_name, struct_name):
    flat_data = []
    for frame in frames:
        flat_data.extend(frame.flatten())
        
    lines = []
    lines.append(f"// Generated by CMT (Color Mapping Tool)")
    lines.append(f"#include \"locale.h\"")
    lines.append(f"")
    
    # Write array
    lines.append(f"const uint8_t {struct_name}_data[] = {{")
    
    # Format array elements neatly
    for i in range(0, len(flat_data), 16):
        chunk = flat_data[i:i+16]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
        
    lines.append(f"}};")
    lines.append(f"")
    
    # Write struct
    lines.append(f"const LHR_MapImage {struct_name} = {{")
    lines.append(f"  .data = {struct_name}_data,")
    lines.append(f"  .width = {width},")
    lines.append(f"  .height = {height},")
    lines.append(f"  .frames = {num_frames},")
    lines.append(f"  .fps = {fps}")
    lines.append(f"}};")
    
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser(description="LHR Color Mapping Tool")
    parser.add_argument("input", help="Input image (GIF/PNG)")
    parser.add_argument("output", help="Output C header file")
    parser.add_argument("--palette", default="core/palette.h", help="Path to palette.h")
    parser.add_argument("--name", default="mapped_image", help="Name of the C struct")
    parser.add_argument("--dither", action="store_true", help="Enable Floyd-Steinberg dithering")
    args = parser.parse_args()
    
    print(f"Loading palette from {args.palette}...")
    palette = load_palette(args.palette)
    
    print(f"Processing image {args.input}...")
    frames, width, height, num_frames, fps = process_image(args.input, palette, dither=args.dither)
    
    print(f"Generating C header {args.output}...")
    c_code = generate_c_header(frames, width, height, num_frames, fps, args.output, args.name)
    
    with open(args.output, 'w') as f:
        f.write(c_code)
        
    print("Done!")

if __name__ == "__main__":
    main()
